default_language_version:
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        exclude: ^(tests|notebooks)

  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        exclude: ^(tests|notebooks)

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: ["python"]
        exclude: ^(tests|notebooks)

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(tests|notebooks)

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
