name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          
          # TODO: Remove this workaround once backtester is fixed
          # 1) Install all your normal requirements except backtester
          grep -v '^backtester==' requirements.txt > req-no-backtester.txt
          pip install -r req-no-backtester.txt
      
          # 2) Ensure the real scikit-learn is present
          pip install scikit-learn==1.6.1
      
          # 3) Install backtester itself, but skip its broken dependencies
          pip install backtester==0.7 --no-deps
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q
